### ISSUE TITLE
报错get config error:1

### ISSUE THREAD

**Issue by xuhuan** [FurionCS/YapiIdeaUploadPlugin#7]
多maven模块的spring项目，misc.xml按照多模块配置了，上传的时候提示
```
get config error:1
```
idea2019.1
插件直接idea的plugin里下载安装的，插件最新版本。

**Comment by FurionCS** [comment]
多模块的版本目前还没上传插件库；请到github下载1.6.2 版本


发自我的 iPad

------------------ 原始邮件 ------------------
发件人: xuhuan <notifications@github.com>
发送时间: 2019年5月13日 22:00
收件人: FurionCS/YapiIdeaUploadPlugin <YapiIdeaUploadPlugin@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[FurionCS/YapiIdeaUploadPlugin] 报错get config error:1 (#7)




多maven模块的spring项目，misc.xml按照多模块配置了，上传的时候提示
get config error:1
idea2019.1
插件直接idea的plugin里下载安装的。

**Comment by xuhuan** [comment]
该问题已解决，出现了另一个问题，新开一个issue。
